### Create Report
POST http://localhost:3000/reports
content-type: application/json

{
    "make": "toyota",
    "model": "corolla",
    "year": 1980,
    "milage": 10000,
    "lat": 0,
    "lng": 0,
    "price": 55000
}
